### ISSUE TITLE
New rule: String required

### ISSUE THREAD

**Issue by timdeschryver** [GooRiOn/Valit#128]
👋 all,

Would it make sense to add a `String.Required` rule, or should `String.MinLength` be used here?
This rule would do the check via `string.IsNullOrWhiteSpace()`.

I can create a PR if this gets expected.

**Comment by paw3lx** [comment]
I think that it's good idea, because other types (int?, float? etc) already has `Required` rule. Of course we can also use `MinLength`, but it will be good to have `Required` rule in every nullable type.

**Comment by GooRiOn** [comment]
Honestly, I'm  little bit surprised that we missed that :D We should go for it for sure 👍

**Comment by GooRiOn** [comment]
@tdeschryver I did this change since I had some free time. Unfortunately I didn't checkout to the new branch (I didn't notice error  that I typed git checkout -b incorrectly) and I pushed changes directly to the develop... Since it's protected branch I can't revert this... Please take a look at this commit and if something will be wrong, I'll create a PR with fixes:

https://github.com/valit-stack/Valit/commit/4116619e2f0e710d0022e73766e2ce702ae350c6

I'm sorry guys :/ My bad :/

**Comment by GooRiOn** [comment]
Ok I did the revert commit :D The PR #130 was created for this change :)
